#!/bin/bash
#killall feedbackserver
#feedbackserver generating &
if [ x$LANG = xzh_CN.UTF-8 ]
then
    gvfs-open "http://bbs.chinauos.com"
else
    gvfs-open "http://bbs.chinauos.com"
fi
#result_tag="deepin-feedback-all-$(date "+%Y%m%d-%H%M%S")"
#output_path=${PWD}/${result_tag}.tar.gz
#pkexec deepin-feedback-cli -o ${output_path}
#killall feedbackserver
#feedbackserver ${result_tag}.tar.gz &
